version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:edge
    environment:
      MANIFEST_BRANCH: "android-9.0"
      # PBRP_BRANCH: '' # OPTIONAL:: If not default 'android-9.0', define other bootable_recovery branch
      VERSION: '2.9.1'
      MAINTAINER: "Lopestorm @lopestom and PBRP Team"
      VENDOR: "BLU"
      CODENAME: "G0130WW"
      FLAVOR: "userdebug"
      TEST_BUILD: "true"
      # PB_OFFICIAL: "true"
      # EXTRA_CMD: "" # OPTIONAL:: MUST USE DOUBLE-QUOTE
      # PB_ENGLISH: "true" # OPTIONAL:: If you want only English Language
      CHANGELOG: |
        - Initial Build
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: "pbrp-9.0"
          context: org-global
